FROM python:3.9-slim-buster
ARG TZ
ENV TZ=$TZ

COPY . /src
WORKDIR /src/src

# hadolint ignore=DL3013
# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install -y entr --no-install-recommends && \
    SETUPTOOLS_SCM_PRETEND_VERSION=dev pip install --no-cache-dir -e .. && \
    groupadd -r etos && useradd -r -m -s /bin/false -g etos etos

USER etos

CMD ["sh", "-c", "find -name '*' -print | entr -r python -u -m suite_starter.suite_starter"]

# DOCKER_CONTEXT is used by ETOS Library to determine whether or not the tool is running in Kubernetes
ENV DOCKER_CONTEXT="ETOS Suite Starter"

LABEL org.opencontainers.image.source=https://github.com/eiffel-community/etos-suite-starter
LABEL org.opencontainers.image.authors=etos-maintainers@googlegroups.com
LABEL org.opencontainers.image.licenses=Apache-2.0